<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWpf>true</UseWpf>
    <AssemblyName>WinDock_Setup</AssemblyName>
    <ApplicationIcon>..\windock.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="..\windock_logo.png" Link="windock_logo.png" />
    <Compile Include="..\NativeBlur.cs" Link="NativeBlur.cs" />
  </ItemGroup>
  <ItemGroup Condition="Exists('..\app_payload_part1.dat')">
    <EmbeddedResource Include="..\app_payload_part1.dat" Link="app_payload_part1.dat" />
    <EmbeddedResource Include="..\app_payload_part2.dat" Link="app_payload_part2.dat" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
